package com.twocircle.server

import kotlinx.datetime.Clock
import kotlinx.datetime.TimeZone
import kotlinx.datetime.toLocalDateTime
import org.jetbrains.exposed.dao.id.LongIdTable
import org.jetbrains.exposed.sql.javatime.timestamp

/**
 * Database table definitions (Exposed ORM).
 *
 * Auto-created on startup by DatabaseFactory.init().
 * UUIDs are used for public-facing IDs (userId, rideId) so clients can
 * generate IDs offline and sync later without collision.
 */

object Users : LongIdTable("users") {
    val email = varchar("email", 255).uniqueIndex()
    val passwordHash = varchar("password_hash", 255)
    val displayName = varchar("display_name", 100)
    val avatarUrl = varchar("avatar_url", 500).nullable()
    val bio = text("bio").nullable()
    val city = varchar("city", 100).nullable()
    val createdAt = timestamp("created_at")
    val updatedAt = timestamp("updated_at")
}

object Rides : LongIdTable("rides") {
    val userId = long("user_id").index()
    val externalId = varchar("external_id", 36).uniqueIndex() // UUID generated by client
    val name = varchar("name", 200)
    val distanceMeters = double("distance_meters")
    val durationSeconds = long("duration_seconds")
    val ascentMeters = double("ascent_meters")
    val descentMeters = double("descent_meters")
    val avgSpeedMps = double("avg_speed_mps")
    val startedAtMs = long("started_at_ms")
    val endedAtMs = long("ended_at_ms").nullable()
    val gpxUrl = varchar("gpx_url", 500).nullable() // S3/MinIO URL
    val isPublic = bool("is_public").default(false)
    val createdAt = timestamp("created_at")
    val updatedAt = timestamp("updated_at")
}

/**
 * Helper: current Instant for Exposed timestamp columns.
 */
fun nowTimestamp(): java.time.Instant = java.time.Instant.now()

fun nowIso() = Clock.System.now().toLocalDateTime(TimeZone.UTC).toString()
