package com.twocircle.bike.feature.map.view

import android.os.Bundle
import androidx.compose.runtime.Composable
import androidx.compose.runtime.DisposableEffect
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.remember
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.viewinterop.AndroidView
import androidx.lifecycle.Lifecycle
import androidx.lifecycle.LifecycleEventObserver
import androidx.lifecycle.compose.LocalLifecycleOwner
import org.maplibre.android.MapLibre
import org.maplibre.android.maps.MapView
import org.maplibre.android.maps.MapLibreMap
import org.maplibre.android.maps.Style

/**
 * MapLibre MapView wrapped for Compose.
 *
 * Why AndroidView and not a pure-Compose map? MapLibre Native is a SurfaceView-based
 * renderer; there is no Compose-native equivalent, and writing one is well out of scope.
 * `AndroidView` is the supported integration path and gives us the View lifecycle hooks
 * the SDK demands.
 *
 * Lifecycle: MapView has its own onStart/onResume/onPause/onStop/onDestroy that MUST be
 * forwarded from the host. We observe the Compose lifecycle owner and call them in the
 * right order. Skipping these leaks GL contexts and crashes on backgrounding — a
 * well-known MapLibre/Mapbox footgun.
 *
 * Style loading: the style JSON is generated by the caller (via MapStyleProvider) and
 * passed in. When [styleJson] changes we re-load — this is how region switches work
 * without recreating the MapView.
 *
 * [onMapReady] fires once after the style has loaded, giving the caller the
 * [MapLibreMap] reference to attach sources/layers/camera. We deliberately pass the raw
 * SDK type here rather than wrapping — adding layers is verbose and benefits from
 * direct SDK access; the [MapController] handles the common camera ops only.
 */
@Composable
fun BikeMap(
    styleJson: String,
    initialCamera: com.twocircle.bike.feature.map.model.MapCamera,
    modifier: Modifier = Modifier,
    onMapReady: (MapLibreMap) -> Unit = {},
) {
    val context = LocalContext.current
    val lifecycleOwner = LocalLifecycleOwner.current

    // MapLibre singleton must be initialised before any MapView is constructed.
    // Idempotent — safe to call on every recomposition.
    remember { MapLibre.getInstance(context) }

    val mapView = remember { MapView(context) }
    val controller = remember { MapController(null) }

    // Forward MapView lifecycle events from the Compose lifecycle owner.
    DisposableEffect(lifecycleOwner) {
        val observer = LifecycleEventObserver { _, event ->
            when (event) {
                Lifecycle.Event.ON_CREATE -> mapView.onCreate(Bundle())
                Lifecycle.Event.ON_START -> mapView.onStart()
                Lifecycle.Event.ON_RESUME -> mapView.onResume()
                Lifecycle.Event.ON_PAUSE -> mapView.onPause()
                Lifecycle.Event.ON_STOP -> mapView.onStop()
                Lifecycle.Event.ON_DESTROY -> mapView.onDestroy()
                else -> Unit
            }
        }
        lifecycleOwner.lifecycle.addObserver(observer)
        onDispose {
            lifecycleOwner.lifecycle.removeObserver(observer)
            controller.detach()
        }
    }

    // Load (or reload) the style whenever it changes. Runs once per style.
    LaunchedEffect(styleJson) {
        mapView.getMapAsync { map ->
            map.setStyle(Style.Builder().fromJson(styleJson)) {
                controller.attach(map)
                map.cameraPosition = org.maplibre.android.camera.CameraPosition.Builder()
                    .target(org.maplibre.android.geometry.LatLng(initialCamera.lat, initialCamera.lon))
                    .zoom(initialCamera.zoom)
                    .bearing(initialCamera.bearing)
                    .tilt(initialCamera.tilt)
                    .build()
                onMapReady(map)
            }
        }
    }

    AndroidView(
        modifier = modifier,
        factory = { mapView },
    )
}
